# Generated by Django 3.2.25 on 2024-07-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_parent'),
        ('profiles', '0002_rename_default_county_userprofile_default_state'),
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user_profile', 'product')},
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user_profile', 'product'], name='wishlist_wi_user_pr_25e9c1_idx'),
        ),
    ]
