# Generated by Django 3.2.25 on 2024-06-20 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_county',
            new_name='default_state',
        ),
    ]
